### ISSUE TITLE
ERROR When run process_data.py

### ISSUE THREAD

**Issue by unflagbear** [nvr-avg/ScePT#4]
when i run 

     python process_data.py

following error is occurred

    Traceback (most recent call last):
      File "process_data.py", line 9, in <module>
        from environment import Environment, Scene, Node
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/environment/__init__.py", line 8, in <module>
        from .map import GeometricMap
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/environment/map.py", line 3, in <module>
        from model.dataset.homography_warper import get_rotation_matrix2d, warp_affine_crop
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/model/__init__.py", line 1, in <module>
        from .ScePT import ScePT
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/model/ScePT.py", line 5, in <module>
        from model.dataset import (
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/model/dataset/__init__.py", line 1, in <module>
        from .dataset import EnvironmentDataset, NodeTypeDataset, clique_dataset, IRL_dataset
      File "/mnt/workspace/opensource/ScePT/experiments/pedestrians/../../ScePT/model/dataset/dataset.py", line 19, in <module>
        from pathos.multiprocessing import ProcessPool as Pool
      File "/home/anaconda3/envs/ScePT/lib/python3.8/site-packages/pathos/__init__.py", line 55, in <module>
        from . import pools
      File "/home/anaconda3/envs/ScePT/lib/python3.8/site-packages/pathos/pools.py", line 31, in <module>
        from pathos.helpers import ProcessPool as _ProcessPool
      File "/home/anaconda3/envs/ScePT/lib/python3.8/site-packages/pathos/helpers/__init__.py", line 9, in <module>
        from . import pp_helper
      File "/home/anaconda3/envs/ScePT/lib/python3.8/site-packages/pathos/helpers/pp_helper.py", line 30, in <module>
        from pp import _Task
    ImportError: cannot import name '_Task' from 'pp' (/home/anaconda3/envs/ScePT/lib/python3.8/site-packages/pp/__init__.py)

**Comment by chenyx09** [comment]
I never encountered this bug, seems like pathos is not installed correctly, can you try reinstalling pathos first and make sure you can import pathos?

**Comment by unflagbear** [comment]
thanks, i reinstall pathos. It worked.
